# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Apps2Samsung.Apps2Samsung
PackageVersion: 2.7.0
InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Apps2Samsung/Apps2Samsung/releases/download/v2.7.0/Apps2Samsung-v2.7.0-win-x64.msi
  InstallerSha256: A5713EBA1DB74577B9934DF4FA840390ECAB500DF6045CE6DE670DB0F18EEF7E
ManifestType: installer
ManifestVersion: 1.12.0










